//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use paperclip::actix::Apiv2Schema;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Apiv2Schema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sex_type")]
pub enum SexType {
    #[sea_orm(string_value = "female")]
    Female,
    #[sea_orm(string_value = "male")]
    Male,
    #[sea_orm(string_value = "other")]
    Other,
}
