version: "3"
services:
  postgres:
    image: postgres
    container_name: specific-postgres
    environment:
      POSTGRES_USER: rust
      POSTGRES_PASSWORD: incubator
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
